"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.cLog = exports.addZeroStart = exports.YoutubePostDownload = exports.YoutubeThumbnailDownload = void 0;
const addZero_1 = require("./tools/addZero");
const consleLog_1 = require("./tools/consleLog");
const youtube_1 = require("./tools/youtube");
console.log((0, youtube_1.youtubeThumbnailDownload)("https://www.youtube.com/channel/UCtb33Ciysb6TEkXaORcVmpg/community?lb=UgkxecTeEsREi3JqSMFP-Vwwx9r_xUPh3E8-", "i.jpg"));
exports.YoutubeThumbnailDownload = youtube_1.youtubeThumbnailDownload;
exports.YoutubePostDownload = youtube_1.youtubePostDownload;
exports.addZeroStart = addZero_1.addZero;
exports.cLog = consleLog_1.consoleLog;
